'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto'),cp=require('node:child_process');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const app=path.resolve(__dirname,'../index.html'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'media-mobile-'));
const server=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(fs.readFileSync(app));});
const digest=b=>crypto.createHash('sha256').update(b).digest('hex');
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined});
 try{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,acceptDownloads:true});await context.addInitScript(()=>{Object.defineProperty(navigator,'canShare',{configurable:true,value:data=>Array.isArray(data.files)});Object.defineProperty(navigator,'share',{configurable:true,value:async data=>{window.__shared=await Promise.all(data.files.map(async f=>({name:f.name,bytes:Array.from(new Uint8Array(await f.arrayBuffer()))})));}});});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=','base64');
 const videoPath=path.join(temp,'演示视频.mp4');cp.execFileSync('ffmpeg',['-hide_banner','-loglevel','error','-f','lavfi','-i','testsrc2=size=1280x720:rate=25','-t','3','-c:v','libx264','-preset','ultrafast','-crf','18','-threads','1',videoPath]);const video=fs.readFileSync(videoPath);assert.ok(video.length>1e6,'demo should split in UI');
 await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('#source-files').setInputFiles([{name:'演示视频.mp4',mimeType:'video/mp4',buffer:video},{name:'COPY-LEAK-TEST.png',mimeType:'image/png',buffer:image}]);await page.locator('#limit').fill('1');await context.setOffline(true);await page.locator('#pack').click();await page.waitForFunction(()=>!document.getElementById('packed').hidden);assert.match(await page.locator('#status').innerText(),/尚未上传/);
 const downloads=[];for(const a of await page.locator('#pack-downloads a').all()){const promise=page.waitForEvent('download');await a.click();const d=await promise,file=path.join(temp,d.suggestedFilename());await d.saveAs(file);downloads.push(file);}
 const manifestPath=downloads.find(f=>f.endsWith('.json')),parts=downloads.filter(f=>f.endsWith('.zip'));const manifest=JSON.parse(fs.readFileSync(manifestPath));assert.equal(manifest.files[0].sha256,digest(video));assert.equal(manifest.files[1].sha256,digest(image));for(const p of parts)assert.ok(fs.statSync(p).size<=1e6);
 const copyPromise=page.waitForEvent('download');await page.locator('#copy-tool').click();const copyDownload=await copyPromise,copyPath=path.join(temp,'copy.html');await copyDownload.saveAs(copyPath);const copyHTML=fs.readFileSync(copyPath,'utf8');assert.ok(!copyHTML.includes('COPY-LEAK-TEST'));assert.ok(!copyHTML.includes('演示视频.mp4'));assert.ok(!copyHTML.includes('href="blob:'));assert.ok(!copyHTML.includes(manifest.bundle));
 const zipPromise=page.waitForEvent('download');await page.locator('#copy-zip').click();const zipDownload=await zipPromise,zipPath=path.join(temp,'tool.zip');await zipDownload.saveAs(zipPath);cp.execFileSync('python3',['-c',"import zipfile,sys; z=zipfile.ZipFile(sys.argv[1]); assert z.namelist()==['index.html']; assert b'COPY-LEAK-TEST' not in z.read('index.html')",zipPath]);
 await page.locator('[data-tab="restore"]').click();await page.locator('#manifest').setInputFiles(manifestPath);await page.locator('#parts').setInputFiles(parts.slice(1));await page.locator('#check').click();await page.waitForFunction(()=>document.getElementById('status').textContent.includes('缺少'));await page.locator('#parts').setInputFiles([...parts].reverse());await page.locator('#merge').click();await page.waitForFunction(()=>!document.getElementById('restored').hidden);
 await page.locator('#restore-downloads .buttons button').nth(1).click();await page.waitForFunction(()=>Array.isArray(window.__shared));assert.equal(await page.evaluate(()=>window.__shared[0].name),'COPY-LEAK-TEST.png');assert.deepEqual(Buffer.from(await page.evaluate(()=>window.__shared[0].bytes)),image);
 const originals=[];for(const a of await page.locator('#restore-downloads a').all()){const promise=page.waitForEvent('download');await a.click();const d=await promise,file=path.join(temp,'restored-'+d.suggestedFilename());await d.saveAs(file);originals.push(fs.readFileSync(file));}assert.equal(digest(originals[0]),digest(video));assert.equal(digest(originals[1]),digest(image));
 await page.locator('[data-tab="channels"]').click();assert.equal(await page.locator('.channel').count(),55);await page.locator('#channel-filter').selectOption('peer');assert.equal(await page.locator('.channel').count(),6);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);
 await context.setOffline(false);page.on('dialog',dialog=>dialog.accept());await page.goto('file://'+copyPath);assert.equal(await page.locator('#status').innerText(),'尚未选择文件。');assert.equal(await page.locator('#pack').isEnabled(),true);assert.equal(await page.locator('.channel').count(),55);assert.equal(await page.locator('#packed').isVisible(),false);
 const qa=path.resolve(__dirname,'../验证记录');fs.mkdirSync(qa,{recursive:true});await page.screenshot({path:path.join(qa,'手机尺寸预览.png'),fullPage:true});await page.setViewportSize({width:360,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 console.log(JSON.stringify({result:'PASS',browser:'Chromium mobile viewport emulation (not a real phone)',sourceVideoBytes:video.length,zipParts:parts.length,checks:['actual MP4 + PNG offline round trip','1MB ZIP ceiling','missing-part rejection','reversed selection order','self-copy no filenames, bundle or Blob URL','publish ZIP accepted by Python','copy file reopens','optional system-share API handoff (mock only)','55 candidates and filters','390px and 360px no horizontal overflow','no JS page errors']},null,2));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>{server.close();fs.rmSync(temp,{recursive:true,force:true});});
