import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,pbkdf2Sync,createCipheriv,randomBytes} from 'node:crypto';
import {readFileSync,mkdtempSync,writeFileSync,readdirSync,existsSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
import worker from '../worker/community.js';
import {BACKUP_TABLES} from '../worker/archive.js';
import {SHA256} from '../worker/sha256.js';
import {database,migrate} from '../scripts/local-adapter.mjs';
const origin='https://tests.invalid',receipt='a'.repeat(64),png=Uint8Array.from([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,1,0,0,0,1,8,6,0,0,0]);
const hash=b=>createHash('sha256').update(b).digest('hex');
function fixture(){const DB=database();migrate(DB,fileURLToPath(new URL('../drizzle',import.meta.url)));const storage=new Map();const env={DB,MODERATOR_EMAIL:'mod@tests.invalid',BUCKET:{async put(key,bytes){storage.set(key,new Uint8Array(await new Response(bytes).arrayBuffer()))},async delete(key){storage.delete(key)},async get(key,opts){const bytes=storage.get(key);if(!bytes)return null;const range=opts?.range?.get('Range')?.match(/^bytes=(\d+)-(\d+)$/);if(range){const offset=Number(range[1]),length=Number(range[2])-offset+1;return {body:bytes.slice(offset,offset+length),size:bytes.length,range:{offset,length}}}return {body:bytes,size:bytes.length}}},ASSETS:{fetch:()=>new Response('static')}};
 async function req(path,method='GET',value,role='',rec=receipt,extra={}){const headers={'Origin':origin,'X-Kanjian-Request':'1',...(rec?{'X-Intake-Receipt':rec}:{}),...(role?{'oai-authenticated-user-id':'user-'+role,'oai-authenticated-user-email':role+'@tests.invalid'}:{}),...extra};if(value!==undefined)headers['Content-Type']='application/json';const response=await worker.fetch(new Request(origin+path,{method,headers,body:value===undefined?undefined:JSON.stringify(value)}),env);return {status:response.status,data:await response.json()};}
 async function create(values={},role=''){const id=crypto.randomUUID();const r=await req('/api/intake','POST',{id,kind:'material',title:'测试机构资料',institution:'测试机构（虚构）',body:'整理公开出处，不作事实认定。',sourceNote:'https://example.org/source',scope:'review',rights:true,...values},role);assert.equal(r.status,201);return id}
 async function upload(iid,values={}){const fid=values.id||crypto.randomUUID(),params=new URLSearchParams({id:fid,name:'test.png',public:values.public?'1':'0',export:values.export?'1':'0'});const response=await worker.fetch(new Request(origin+'/api/intake/'+iid+'/files?'+params,{method:'POST',headers:{Origin:origin,'X-Kanjian-Request':'1','X-Intake-Receipt':receipt,'X-Media-Consent':'confirmed','X-File-Size':String(png.length),'X-File-SHA256':values.sha||hash(png),'Content-Type':'image/png'},body:png}),env);return {status:response.status,data:await response.json(),id:fid};}
 const publish=(iid,files=[],options={})=>req('/api/intake/mod/action','POST',{id:iid,action:'publish',message:'已核对公开范围，来源仍需持续核对。',name:'虚构机构 · 测试专用',summary:'仅用于自动化验收',body:'无真实指控或当事人信息。',verification:'来源与授权已检查，事实未认定。',sources:[{url:'https://example.org/source',label:'测试来源'}],fileIds:files,mediaReviewed:true,...options},'mod');
 return {DB,env,storage,req,create,upload,publish};}

test('私人回执跨设备读取；错误回执、跨站、普通账号不能越权，草稿不进管理员队列',async()=>{const f=fixture(),i=await f.create();assert.equal((await f.req('/api/intake/'+i)).status,200);assert.equal((await f.req('/api/intake/'+i,'GET',undefined,'','b'.repeat(64))).status,404);assert.equal((await f.req('/api/intake/'+i,'GET',undefined,'mod','')).status,404);assert.equal((await f.req('/api/intake/mod/queue','GET',undefined,'mod')).data.items.length,0);assert.equal((await f.req('/api/intake/mod/queue','GET',undefined,'member')).status,403);assert.equal((await f.req('/api/intake/'+i,'PATCH',{},'',receipt,{Origin:'https://evil.invalid'})).status,403);const stored=f.DB.raw.prepare('SELECT receipt_hash FROM intake').get();assert.notEqual(stored.receipt_hash,receipt);assert.ok(!JSON.stringify((await f.req('/api/intake/'+i)).data).includes(receipt));f.DB.raw.close()});
test('账号与回执可分别查看；草稿版本防止覆盖，私人核对不能变成公开档案',async()=>{const f=fixture(),i=await f.create({},'author');assert.equal((await f.req('/api/intake/'+i,'GET',undefined,'author','')).status,200);assert.equal((await f.req('/api/intake/mine','GET',undefined,'author','')).data.items.length,1);assert.equal((await f.req('/api/intake/'+i,'PATCH',{title:'补充说明',body:'更新后的说明',version:99})).status,409);assert.equal((await f.req('/api/intake/'+i+'/submit','POST',{})).data.status,'pending');assert.equal((await f.req('/api/intake/'+i+'/submit','POST',{})).data.duplicate,true);assert.equal((await f.publish(i)).status,403);const d=(await f.req('/api/archive/records','GET',undefined,'','')).data;assert.equal(d.items.length,0);f.DB.raw.close()});
test('流式附件校验、重复上传幂等，管理员只能在提交后读取；公开和导出授权分别执行',async()=>{const f=fixture(),i=await f.create({scope:'public',allowExport:true});const bad=await f.upload(i,{sha:'f'.repeat(64)});assert.equal(bad.status,503);assert.equal(f.storage.size,0);const priv=await f.upload(i),pub=await f.upload(i,{public:true,export:true});assert.equal(pub.status,201);assert.equal((await f.upload(i,{id:pub.id,public:true,export:true})).data.duplicate,true);assert.equal((await f.req('/api/intake/files/'+pub.id,'GET',undefined,'mod','')).status,404);await f.req('/api/intake/'+i+'/submit','POST',{});assert.equal((await f.publish(i,[priv.id])).status,403);assert.equal((await f.publish(i,[pub.id],{mediaReviewed:false})).status,400);const p=await f.publish(i,[pub.id]);assert.equal(p.status,200);const d=(await f.req('/api/archive/records/'+p.data.recordId+'/export','GET',undefined,'','')).data;assert.equal(d.attachments.length,1);for(const value of ['receipt_hash','storage_key','source_note','user-author'])assert.ok(!JSON.stringify(d).includes(value));const bytes=await worker.fetch(new Request(origin+d.attachments[0].url,{headers:{Range:'bytes=0-7'}}),f.env);assert.equal(bytes.status,206);assert.equal((await bytes.arrayBuffer()).byteLength,8);await f.req('/api/intake/'+i,'DELETE');assert.equal((await f.req('/api/archive/records/'+p.data.recordId,'GET',undefined,'','')).status,404);assert.equal((await worker.fetch(new Request(origin+d.attachments[0].url),f.env)).status,404);assert.ok(f.storage.size>0);f.DB.raw.close()});
test('反馈只进入私人队列，要求补充后仍可更新和重提，处理有理由',async()=>{const f=fixture(),i=await f.create({kind:'feedback'});await f.req('/api/intake/'+i+'/submit','POST',{});assert.equal((await f.req('/api/intake/mod/action','POST',{id:i,action:'needs_changes',message:''},'mod')).status,400);await f.req('/api/intake/mod/action','POST',{id:i,action:'needs_changes',message:'请补充来源页面和具体位置'},'mod');const r=(await f.req('/api/intake/'+i)).data;assert.equal(r.status,'needs_changes');await f.req('/api/intake/'+i,'PATCH',{kind:'feedback',title:r.title,body:'补充了更正位置',version:r.version,rights:true});await f.req('/api/intake/'+i+'/submit','POST',{});assert.equal((await f.publish(i)).status,403);const rows=(await f.req('/api/intake/mod/queue','GET',undefined,'mod')).data.items;assert.equal(rows.length,1);f.DB.raw.close()});
test('私有备份拒绝普通用户，分页无截断，可加密恢复到空目录；缺卷拒绝建立不完整副本',async()=>{const f=fixture(),i=await f.create(),file=await f.upload(i);assert.equal((await f.req('/api/backup/catalog')).status,403);assert.equal((await f.req('/api/backup/catalog','GET',undefined,'member')).status,403);assert.equal((await f.req('/api/backup/table?name=sqlite_schema','GET',undefined,'mod')).status,400);for(let n=0;n<60;n++)f.DB.raw.prepare('INSERT INTO limits VALUES(?,?,?)').run('page-test-'+n,1,n);const tables={};for(const name of BACKUP_TABLES){let after='';tables[name]=[];do{const d=(await f.req('/api/backup/table?'+new URLSearchParams({name,after}),'GET',undefined,'mod')).data;tables[name].push(...d.rows);after=d.next||''}while(after)}assert.ok(tables.limits.length>=60);const area=mkdtempSync(join(tmpdir(),'jiewangyin-restore-')),parts=area,password='test-password-local-only';const encrypt=v=>{const salt=randomBytes(16),iv=randomBytes(12),key=pbkdf2Sync(password,salt,210000,32,'sha256'),c=createCipheriv('aes-256-gcm',key,iv),bytes=Buffer.concat([c.update(JSON.stringify(v)),c.final(),c.getAuthTag()]);return JSON.stringify({format:'jiewangyin-private-encrypted-v1',iterations:210000,salt:salt.toString('base64'),iv:iv.toString('base64'),ciphertext:bytes.toString('base64')})};const partName='intake-'+file.id+'-00001.encrypted.json',snapshot={format:'kanjian-private-backup-v1',tables,media:[{kind:'intake',id:file.id,size:png.length,storageKey:'intake/'+file.id,sha256:hash(png),parts:[{name:partName,offset:0,size:png.length}]}]};writeFileSync(join(area,'manifest.json'),encrypt(snapshot));writeFileSync(join(area,partName),encrypt({format:'kanjian-private-media-part-v1',kind:'intake',id:file.id,size:png.length,offset:0,sha256:hash(png),data:Buffer.from(png).toString('base64')}));const schema=readdirSync(new URL('../drizzle',import.meta.url)).filter(s=>s.endsWith('.sql')).sort().map(s=>readFileSync(new URL('../drizzle/'+s,import.meta.url),'utf8')).join('\n');writeFileSync(join(area,'schema.sql'),schema);const run=out=>spawnSync(process.execPath,[fileURLToPath(new URL('../scripts/restore-private.mjs',import.meta.url)),join(area,'manifest.json'),parts,out,join(area,'schema.sql')],{input:password+'\n',encoding:'utf8'});const output=join(area,'restored');const result=run(output);assert.equal(result.status,0,result.stderr);const restored=database(join(output,'community.sqlite3'));assert.equal(restored.raw.prepare('SELECT count(*) n FROM intake').get().n,1);restored.raw.close();assert.equal(hash(readFileSync(join(output,'media','intake_'+file.id))),hash(png));rmSync(join(area,partName));const missing=join(area,'missing');assert.notEqual(run(missing).status,0);assert.equal(existsSync(missing),false);rmSync(area,{recursive:true});f.DB.raw.close()});
test('来源目录完整、字段白名单及地区解析回归；分块SHA256与标准库一致',()=>{const d=JSON.parse(readFileSync(new URL('../dist/source-catalog.json',import.meta.url)));assert.equal(d.institutions.length,1251);assert.equal(new Set(d.institutions.map(r=>r.id)).size,1251);const byid=Object.fromEntries(d.institutions.map(r=>[r.id,r]));assert.equal(byid['INST-0614'].region,'河南');assert.equal(byid['INST-0060'].region,'河南');assert.equal(byid['INST-0464'].region,'湖南');for(const r of d.institutions){assert.equal(r.verification,'待核对');for(const key of ['contact','HMaster','scandal','experience','address_raw','lat','lng'])assert.ok(!(key in r));}const bytes=randomBytes(500003),sha=new SHA256();for(let n=0;n<bytes.length;n+=17)sha.update(bytes.subarray(n,n+17));assert.equal(sha.hex(),hash(bytes))});
