import test from 'node:test';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import worker from '../worker/community.js';
import {database,migrate} from '../scripts/local-adapter.mjs';
const users={a:['test-private-author','author@testing.invalid'],b:['test-private-reader','reader@testing.invalid'],mod:['test-private-moderator','moderator@testing.invalid']};
const png=new Uint8Array([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82,0,0,0,1,0,0,0,1,8,6,0,0,0]);
function fixture(){const DB=database();migrate(DB,fileURLToPath(new URL('../drizzle',import.meta.url)));const media=new Map();const BUCKET={async put(k,v){media.set(k,new Uint8Array(await new Response(v).arrayBuffer()))},async delete(k){media.delete(k)},async get(k,options){const b=media.get(k);if(!b)return null;const range=options?.range?.get('Range')?.match(/^bytes=(\d+)-(\d+)$/);if(range){const offset=Number(range[1]),length=Number(range[2])-offset+1;return {body:b.slice(offset,offset+length),size:b.length,range:{offset,length}}}return {body:b,size:b.length}}};const env={DB,BUCKET,MODERATOR_EMAIL:users.mod[1],ASSETS:{fetch:()=>new Response('static')}};
 async function req(path,method='GET',data,user,extra={}){const headers=new Headers({'X-Kanjian-Request':'1','Origin':'https://test.invalid'});if(user){headers.set('oai-authenticated-user-id',users[user][0]);headers.set('oai-authenticated-user-email',users[user][1])}let payload;if(data!==undefined){headers.set('Content-Type','application/json');payload=JSON.stringify(data)}for(const [k,v]of Object.entries(extra))v===null?headers.delete(k):headers.set(k,v);const response=await worker.fetch(new Request('https://test.invalid'+path,{method,headers,body:payload}),env);return {status:response.status,data:await response.json(),headers:response.headers};}
 async function profile(u){return req('/api/community/profile','POST',{nickname:u==='mod'?'测试管理员':'测试者'+u,acceptRules:true},u)}
 async function draft(u='a',v={}){const r=await req('/api/community/topics','POST',{title:'如何整理公开资料',body:'希望了解如何保存来源与版本。',category:'资料整理',...v},u);assert.equal(r.status,201);return r.data.id}
 async function submit(t,u='a'){return req('/api/community/topics/'+t+'/submit','POST',{},u)}
 async function mod(t,action='approve',v={}){return req('/api/community/mod/action','POST',{targetType:'topic',targetId:t,action,reason:'测试检查公开范围',...v},'mod')}
 async function publish(v={}){await profile('a');await profile('mod');const t=await draft('a',v);assert.equal((await submit(t)).status,200);assert.equal((await mod(t)).status,200);return t}
 async function upload(t,u='a',options={}){const headers=new Headers({'Origin':'https://test.invalid','X-Kanjian-Request':'1','X-Media-Consent':'confirmed','Content-Type':'image/png','X-File-Size':String(png.length),'oai-authenticated-user-id':users[u][0],'oai-authenticated-user-email':users[u][1],...options.headers});const r=await worker.fetch(new Request('https://test.invalid/api/community/topics/'+t+'/attachments?name=test.png&visibility='+(options.public?'public':'private')+'&export='+(options.export?'1':'0'),{method:'POST',headers,body:options.bytes||png}),env);return {status:r.status,data:await r.json()}}
 return {DB,env,media,req,profile,draft,submit,mod,publish,upload};}

test('匿名、跨站请求和普通用户均不能冒充写入或审核',async()=>{const f=fixture();assert.equal((await f.req('/api/community/topics','POST',{})).status,401);assert.equal((await f.req('/api/community/profile','POST',{},'a',{'Origin':'https://evil.invalid'})).status,403);assert.equal((await f.req('/api/community/profile','POST',{},'a',{'X-Kanjian-Request':null})).status,403);assert.equal((await f.req('/api/community/mod/queue','GET',undefined,'a')).status,403);assert.equal((await f.req('/api/community/profile','POST',{nickname:'本站管理员',acceptRules:true},'a')).status,400);assert.equal((await f.req('/api/community/profile','POST',{nickname:'测试昵称',acceptRules:false},'a')).status,400);f.DB.raw.close()});
test('昵称公约与草稿保存在数据库，其他用户与管理员均不能访问未提交草稿',async()=>{const f=fixture();await f.profile('a');await f.profile('b');await f.profile('mod');const t=await f.draft();assert.equal((await f.req('/api/community/topics/'+t,'GET',undefined,'a')).status,200);assert.equal((await f.req('/api/community/topics/'+t,'GET',undefined,'b')).status,404);assert.equal((await f.req('/api/community/topics/'+t,'GET',undefined,'mod')).status,404);assert.equal((await f.req('/api/community/mine','GET',undefined,'a')).data.topics[0].id,t);const me=JSON.stringify((await f.req('/api/community/me','GET',undefined,'a')).data);assert.ok(!me.includes(users.a[0])&&!me.includes(users.a[1]));assert.equal((await f.req('/api/community/topics/'+t,'PATCH',{title:'越权'},'b')).status,404);f.DB.raw.close()});
test('首次提交进入审核，重复提交幂等；审核后才公开并记录通知',async()=>{const f=fixture();await f.profile('a');await f.profile('mod');const t=await f.draft();assert.equal((await f.submit(t)).data.status,'pending');assert.equal((await f.submit(t)).data.status,'pending');assert.equal((await f.req('/api/community/topics/'+t)).status,404);assert.equal((await f.mod(t)).status,200);assert.equal((await f.req('/api/community/topics/'+t)).data.status,'published');assert.equal((await f.submit(t)).status,409);assert.equal((await f.req('/api/community/mine','GET',undefined,'a')).data.notices.length,1);assert.equal((await f.req('/api/community/mod/queue','GET',undefined,'mod')).data.audit.length,1);f.DB.raw.close()});
test('回复引用需属于已公开的同一讨论，普通回复公开，私人联系方式进入待审',async()=>{const f=fixture(),t=await f.publish();await f.profile('b');assert.equal((await f.req('/api/community/topics/'+t+'/reply','POST',{body:'补充',parent:'nonexistent-reply'},'b')).status,400);const r=await f.req('/api/community/topics/'+t+'/reply','POST',{body:'可以先记录原始链接。'},'b');assert.equal(r.data.status,'published');f.DB.raw.exec('DELETE FROM limits');const p=await f.req('/api/community/topics/'+t+'/reply','POST',{body:'请联系13812345678',parent:r.data.id},'b');assert.equal(p.data.status,'pending');assert.equal((await f.req('/api/community/topics/'+t)).data.replies.length,1);assert.equal((await f.req('/api/community/topics/'+t,'GET',undefined,'b')).data.replies.length,2);assert.equal((await f.req('/api/community/mine','GET',undefined,'a')).data.notices.length,2);f.DB.raw.close()});
test('逐人传播授权：根帖不能替回复授权，导出不含私人身份或存储键',async()=>{const f=fixture(),t=await f.publish({allowExport:true});await f.profile('b');await f.req('/api/community/topics/'+t+'/reply','POST',{body:'不授权打包的回复'},'b');f.DB.raw.exec('DELETE FROM limits');await f.req('/api/community/topics/'+t+'/reply','POST',{body:'明确授权的回复',allowExport:true},'b');const d=(await f.req('/api/community/topics/'+t+'/export')).data;assert.equal(d.replies.length,1);assert.equal(d.replies[0].body,'明确授权的回复');const raw=JSON.stringify(d);for(const value of [...users.a,...users.b,'storage_key','reason','accepted_rules'])assert.ok(!raw.includes(value),value);const t2=await f.draft('a');f.DB.raw.exec('DELETE FROM limits');await f.submit(t2);assert.equal((await f.req('/api/community/topics/'+t2+'/export')).status,403);f.DB.raw.close()});
test('多人举报及重复举报不会自动下架，处理有理由和作者申诉',async()=>{const f=fixture(),t=await f.publish();await f.profile('b');const payload={kind:'report',targetType:'topic',targetId:t,reason:'来源不清',details:'请核对'};const c=await f.req('/api/community/cases','POST',payload,'b');const duplicate=await f.req('/api/community/cases','POST',payload,'b');assert.equal(duplicate.data.id,c.data.id);assert.equal(duplicate.data.duplicate,true);await f.req('/api/community/cases','POST',payload,'a');assert.equal((await f.req('/api/community/topics/'+t)).status,200);assert.equal((await f.mod(t,'hide',{reason:''})).status,400);await f.mod(t,'hide');assert.equal((await f.req('/api/community/topics/'+t)).status,404);const appeal=await f.req('/api/community/cases','POST',{...payload,kind:'appeal',reason:'补充来源'},'a');assert.equal(appeal.status,201);assert.equal((await f.req('/api/community/cases','POST',{...payload,kind:'appeal'},'b')).status,404);assert.equal((await f.req('/api/community/mine','GET',undefined,'b')).data.cases.length,1);await f.req('/api/community/mod/action','POST',{targetType:'case',targetId:appeal.data.id,action:'resolve',reason:'已查看补充资料'},'mod');assert.equal((await f.req('/api/community/mine','GET',undefined,'a')).data.cases.find(x=>x.id===appeal.data.id).decision,'已查看补充资料');f.DB.raw.close()});
test('附件须声明提交权利，默认私人；管理员不能读取未提交附件',async()=>{const f=fixture();await f.profile('a');await f.profile('b');await f.profile('mod');const t=await f.draft();assert.equal((await f.upload(t,'a',{headers:{'X-Media-Consent':'no'}})).status,400);assert.equal((await f.upload(t,'b')).status,404);const a=await f.upload(t);assert.equal(a.status,201);const path='/api/attachments/'+a.data.id;assert.equal((await worker.fetch(new Request('https://test.invalid'+path),f.env)).status,404);assert.equal((await worker.fetch(new Request('https://test.invalid'+path,{headers:{'oai-authenticated-user-id':users.mod[0],'oai-authenticated-user-email':users.mod[1]}}),f.env)).status,404);await f.submit(t);await f.mod(t);assert.equal((await worker.fetch(new Request('https://test.invalid'+path),f.env)).status,404);assert.equal((await f.req('/api/community/topics/'+t)).data.attachments.length,0);assert.equal(f.DB.raw.prepare('SELECT consent_rules FROM attachments').get().consent_rules,'2026-10-09-v1');f.DB.raw.close()});
test('公开附件需要检查才能发布，可播放范围读取，撤回停止公开与导出',async()=>{const f=fixture();await f.profile('a');await f.profile('mod');const t=await f.draft('a',{allowExport:true}),a=await f.upload(t,'a',{public:true,export:true});await f.submit(t);assert.equal((await f.mod(t)).status,400);assert.equal((await f.mod(t,'approve',{mediaReviewed:true})).status,200);const path='/api/attachments/'+a.data.id;const res=await worker.fetch(new Request('https://test.invalid'+path,{headers:{Range:'bytes=0-7'}}),f.env);assert.equal(res.status,206);assert.equal((await res.arrayBuffer()).byteLength,8);assert.equal(res.headers.get('Content-Range'),'bytes 0-7/'+png.length);assert.equal((await f.req('/api/community/topics/'+t+'/export')).data.attachments.length,1);await f.req(path,'DELETE',undefined,'a');assert.equal((await worker.fetch(new Request('https://test.invalid'+path),f.env)).status,404);assert.equal((await f.req('/api/community/topics/'+t+'/export')).data.attachments.length,0);assert.equal(f.media.size,1,'撤回只是停止展示，未假称删除原件');f.DB.raw.close()});
test('禁止伪装文件及错误大小，上传失败可恢复，附件与实际存储配额受限',async()=>{const f=fixture();await f.profile('a');const t=await f.draft();assert.equal((await f.upload(t,'a',{bytes:new TextEncoder().encode('<script>')})).status,415);assert.equal((await f.upload(t,'a',{headers:{'X-File-Size':'999999999'}})).status,413);assert.equal((await f.upload(t,'a',{headers:{'X-File-Size':'80'}})).status,503);f.DB.raw.exec('DELETE FROM limits');for(let i=0;i<5;i++)assert.equal((await f.upload(t)).status,201);f.DB.raw.exec('DELETE FROM limits');assert.equal((await f.upload(t)).status,201);assert.equal((await f.upload(t)).status,413);assert.equal(f.DB.raw.prepare("SELECT count(*) AS n FROM attachments WHERE status='ready'").get().n,6);f.DB.raw.close()});
test('已有正常帖子用户的新公开附件仍需审核；不带争议和附件的正常主题可以直接发布',async()=>{const f=fixture();await f.publish();f.DB.raw.exec('UPDATE topics SET created=created-90000');const t=await f.draft();f.DB.raw.exec('DELETE FROM limits');assert.equal((await f.submit(t)).data.status,'published');const t2=await f.draft();await f.upload(t2,'a',{public:true});f.DB.raw.exec('DELETE FROM limits');assert.equal((await f.submit(t2)).data.status,'pending');f.DB.raw.close()});
test('回复限频、慢速模式和禁言由服务器执行，禁言不阻止查看申诉',async()=>{const f=fixture(),t=await f.publish();await f.profile('b');assert.equal((await f.req('/api/community/topics/'+t+'/reply','POST',{body:'第一条'},'b')).status,201);assert.equal((await f.req('/api/community/topics/'+t+'/reply','POST',{body:'重复刷屏'},'b')).status,429);await f.mod(t,'slow',{seconds:120});f.DB.raw.exec('DELETE FROM limits');assert.equal((await f.req('/api/community/topics/'+t+'/reply','POST',{body:'慢速规则'},'b')).status,429);const p=(await f.req('/api/community/me','GET',undefined,'a')).data.profile;await f.req('/api/community/mod/action','POST',{targetType:'profile',targetId:p.publicId,action:'suspend',days:1,reason:'测试重复广告'},'mod');assert.equal((await f.req('/api/community/topics','POST',{title:'新帖'},'a')).status,403);await f.mod(t,'hide');assert.equal((await f.req('/api/community/cases','POST',{kind:'appeal',targetType:'topic',targetId:t,reason:'申请说明'},'a')).status,201);assert.equal((await f.req('/api/community/mine','GET',undefined,'a')).status,200);f.DB.raw.close()});
test('正文转草稿立即停止公开；撤回及未知草稿申诉边界正确',async()=>{const f=fixture(),t=await f.publish({allowExport:true});await f.req('/api/community/topics/'+t,'PATCH',{title:'修订正文',body:'正在补充来源',category:'资料整理'},'a');assert.equal((await f.req('/api/community/topics/'+t)).status,404);assert.equal((await f.req('/api/community/cases','POST',{kind:'appeal',targetType:'topic',targetId:t,reason:'未处理'},'a')).status,404);await f.req('/api/community/topics/'+t,'DELETE',undefined,'a');assert.equal((await f.req('/api/community/topics/'+t)).status,404);assert.equal((await f.req('/api/community/export')).data.topics.length,0);f.DB.raw.close()});
test('服务器拒绝超长请求、非法来源及错误JSON；静态页面带基本安全头',async()=>{const f=fixture();await f.profile('a');assert.equal((await f.req('/api/community/topics','POST',{body:'a'.repeat(160000)},'a')).status,413);assert.equal((await f.req('/api/community/topics','POST',{source:'javascript:alert(1)'},'a')).status,400);const r=await worker.fetch(new Request('https://test.invalid/',{method:'GET'}),f.env);assert.equal(r.headers.get('X-Content-Type-Options'),'nosniff');f.DB.raw.close()});

test('隐藏后不能通过改成普通正文绕过重新审核',async()=>{const f=fixture(),t=await f.publish();await f.mod(t,'hide');await f.req('/api/community/topics/'+t,'PATCH',{title:'重新补充',body:'不带风险关键词的文字',category:'资料整理'},'a');f.DB.raw.exec('DELETE FROM limits');assert.equal((await f.submit(t)).data.status,'pending');assert.equal((await f.req('/api/community/topics/'+t)).status,404);f.DB.raw.close()});
