const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert'),{webcrypto}=require('crypto');
const dir=path.join(__dirname,'../dist'),elements=new Map(),handlers={};
function element(id){if(!elements.has(id))elements.set(id,{id,innerHTML:'',textContent:'',value:id==='province'||id==='city'||id==='material-kind'?'all':'',dataset:{},hidden:false,setAttribute(){},removeAttribute(){},addEventListener(){},focus(){},pause(){},classList:{toggle(){}},append(){},getBoundingClientRect(){return {left:0,right:500,top:0,bottom:800}},showModal(){this.open=true},close(){this.open=false}});return elements.get(id)}
const document={getElementById:element,querySelector:()=>element('query-element'),querySelectorAll:()=>[],addEventListener:(name,fn)=>(handlers[name]??=[]).push(fn),body:{append(){}},title:''};
const context=vm.createContext({window:{scrollTo(){},scrollY:0,addEventListener(){},KANJIAN_DATA:null,KANJIAN_MAP:null},document,location:{hash:'#home',href:'https://example.test/index.html#home',protocol:'https:',hostname:'example.test'},navigator:{},URL,Blob,Uint8Array,Uint32Array,DataView,TextEncoder,crypto:webcrypto,fetch:async()=>({ok:true,json:async()=>({signedIn:false,profile:null,topics:[]})}),setTimeout(){return 1},clearTimeout(){},console});
for(const file of ['data.js','map-data.js','source-catalog.js','icons.js','sha256.js','app.js','views.js','drafts.js','community.js','intake.js','archive-ui.js','backup-ui.js','pwa.js','actions.js']){const source=fs.readFileSync(path.join(dir,file),'utf8');new vm.Script(source,{filename:file}).runInContext(context)}
const run=s=>vm.runInContext(s,context),routes=['home','browse','institution/demo-a','material/demo-004','experiences','story/story-a','participate','provide','mutual','topic/topic-a','topic-draft','feedback/demo-a','review','about','source-example','material/missing','institution/INST-0614','access','intake-status','intake-mod','backup','archive/test-record'];
for(const route of routes){context.location.hash='#'+route;run('route()');const html=element('main').innerHTML;assert(html.length>100,'empty '+route);assert(!html.includes('undefined')&&!html.includes('NaN'),'bad '+route)}
run("location.hash='#home';route();updateRegion('山东')");assert(element('results-count').textContent.includes('来源记录'));assert(element('institution-list').innerHTML.includes('待核对'));assert(!element('institution-list').innerHTML.includes('示例机构 B'));
run("city='青岛市';renderResults()");assert(element('institution-list').innerHTML.includes('青岛'));
run("city='all';query='不存在的机构';renderResults()");assert(element('institution-list').innerHTML.includes('空白地区不代表'));
assert(run("esc('<script>')")==='&lt;script&gt;');
for(let step=1;step<=3;step++){run('draftStep='+step);assert(run('renderProvide()').includes('保存本机草稿'))}
const manifest=JSON.parse(run('JSON.stringify(draftManifest())'));assert(manifest.isSubmission===false&&manifest.isPublic===false);
assert(run("renderReview()").includes('disabled'));assert(run('renderAbout()').includes('1251'));assert(!run('renderHome()').includes('正在加载'));
(async()=>{const blob=run("zipFiles([{name:'说明.txt',bytes:new TextEncoder().encode('测试资料')}])");fs.writeFileSync(path.join(__dirname,'test-zip.tmp'),Buffer.from(await blob.arrayBuffer()));console.log(JSON.stringify({routesChecked:routes.length,regionAndCityFilters:true,localDraftStages:3,privateDraftMarkers:true,zipWritten:true}));})();
